var FIELD_WIDTH = 11;
var FIELD_HEIGHT = 20;
var FIELD_TOTAL_HEIGHT = 40;

var ZOOM = 2;
var BLOCK_BORDER = 2;
var BLOCK_SIZE = 16;

var VISUAL_HEIGHT = BLOCK_SIZE * ZOOM;
VISUAL_HEIGHT += BLOCK_BORDER * ZOOM * 2;
VISUAL_HEIGHT *= FIELD_HEIGHT;
VISUAL_HEIGHT += BLOCK_BORDER*ZOOM;

var VISUAL_WIDTH = ((BLOCK_SIZE*ZOOM)+(BLOCK_BORDER+ZOOM)) * (FIELD_WIDTH + 10);

var COLOR_BLOCK_FULL = '#BFCD99';
var COLOR_BLOCK_EMPTY = '#000000';
var COLOR_BLOCK_GHOST = '#373837';

//O J L S T Z I
var INITIALX = 4;
var INITIALY = 20;

var LINE_COUNT = 0;

