var FIELD_WIDTH = 11;
var FIELD_HEIGHT = 20;
var FIELD_TOTAL_HEIGHT = 40;

var ZOOM = 2;
var BLOCK_BORDER = 2;
var BLOCK_SIZE = 16;

var VISUAL_HEIGHT = BLOCK_SIZE * ZOOM;
VISUAL_HEIGHT += BLOCK_BORDER * ZOOM * 2;
VISUAL_HEIGHT *= FIELD_HEIGHT;
VISUAL_HEIGHT += BLOCK_BORDER*ZOOM;

var VISUAL_WIDTH = ((BLOCK_SIZE*ZOOM)+(BLOCK_BORDER+ZOOM)) * (FIELD_WIDTH + 10);

var BLOCK_COLOR_FULL = '#bfcd99';
var BLOCK_COLOR_EMPTY = '#000000';
var BLOCK_COLOR_GHOST = '#373837';

//o j l s t z i
var INITIALX = 4;
var INITIALY = 20;

var line_count = 0;

